# Generated by Django 4.2.6 on 2023-10-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(),
        ),
    ]
