# Generated by Django 4.2.6 on 2023-10-26 17:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
